// Recensioni e risposte di fantasia per la home: tono diverso per ogni caso, settori diversi.
export type EsempioRisposta = { tipo: "Positiva" | "Con una critica" | "Negativa"; settore: string; autore: string; voto: number; testo: string; risposta: string };

export const ESEMPI_RISPOSTE: EsempioRisposta[] = [
  { tipo: "Positiva", settore: "Bar", autore: "Giulia M.", voto: 5, testo: "Cappuccino buonissimo e cornetti appena sfornati. Personale gentilissimo, ormai ci passo ogni mattina.", risposta: "Grazie Giulia, che bello leggerti. Ti aspettiamo domattina: il cornetto al pistacchio esce verso le 8." },
  { tipo: "Negativa", settore: "Ristorante", autore: "Luca R.", voto: 2, testo: "Abbiamo aspettato quaranta minuti per due primi. Peccato, il posto è bello.", risposta: "Buongiorno Luca, ha ragione e ci scusiamo: sabato eravamo in difficoltà in cucina. Ci farebbe piacere rimediare, ci scriva quando torna." },
  { tipo: "Con una critica", settore: "Parrucchiere", autore: "Sara T.", voto: 4, testo: "Taglio perfetto, esattamente come lo volevo. Unica cosa: ho aspettato un po' nonostante l'appuntamento.", risposta: "Grazie Sara, felici che il taglio ti piaccia. Hai ragione sull'attesa: stiamo distanziando meglio gli appuntamenti. A presto." },
  { tipo: "Positiva", settore: "Idraulico", autore: "Franco B.", voto: 5, testo: "Chiamato la mattina per una perdita sotto il lavello, alle 11 era già tutto sistemato. Preciso e pulito.", risposta: "Grazie Franco, ci fa piacere che sia andato tutto bene. Per qualsiasi cosa sa dove trovarci." },
  { tipo: "Negativa", settore: "Pizzeria", autore: "Anna P.", voto: 1, testo: "Pizza arrivata fredda a domicilio, dopo un'ora.", risposta: "Gentile Anna, ci dispiace davvero: non è il servizio che vogliamo dare. Ci scriva o ci chiami, vorremmo capire cosa è successo e rimediare." },
  { tipo: "Positiva", settore: "Centro estetico", autore: "Martina L.", voto: 5, testo: "Ambiente rilassante e trattamento viso fantastico. Mi sono sentita coccolata dall'inizio alla fine.", risposta: "Grazie Martina, è proprio quello che vogliamo far provare. Ti aspettiamo per il prossimo trattamento." },
  { tipo: "Con una critica", settore: "Hotel e B&B", autore: "Thomas K.", voto: 3, testo: "Camera pulita e posizione comoda, ma il wifi in camera era debolissimo.", risposta: "Grazie Thomas per il suggerimento. Il segnale nelle camere al secondo piano è un punto da migliorare e ci stiamo lavorando. Speriamo di ospitarla ancora." },
  { tipo: "Positiva", settore: "Palestra", autore: "Davide S.", voto: 5, testo: "Istruttori preparati e sempre disponibili. In tre mesi ho visto risultati veri.", risposta: "Grazie Davide, il merito è soprattutto della tua costanza. Ci vediamo in sala." },
  { tipo: "Negativa", settore: "Meccanico", autore: "Roberto F.", voto: 2, testo: "Preventivo al telefono diverso dal conto finale.", risposta: "Buongiorno Roberto, ci dispiace per l'incomprensione sul prezzo. Ci contatti in officina: vogliamo ripercorrere insieme il lavoro fatto e chiarire ogni voce." },
  { tipo: "Positiva", settore: "Pasticceria", autore: "Chiara D.", voto: 5, testo: "Torta di compleanno bellissima e buonissima, tutti hanno chiesto dove l'avevamo presa.", risposta: "Grazie Chiara, siamo felici che la festa sia andata alla grande. Alla prossima occasione da festeggiare." },
  { tipo: "Con una critica", settore: "Negozio", autore: "Paola N.", voto: 4, testo: "Bei capi e commessa gentile, ma il camerino era troppo piccolo.", risposta: "Grazie Paola, la sua osservazione ci è utile: stiamo valutando come rendere i camerini più comodi. A presto in negozio." },
  { tipo: "Positiva", settore: "Massaggi", autore: "Elena V.", voto: 5, testo: "Massaggio decontratturante eccezionale, la schiena finalmente sciolta dopo settimane.", risposta: "Grazie Elena, che bello saperlo. Se la tensione torna, sai dove trovarci." },
];
